---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phptest1
  labels:
    app: phptest1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phptest1
  template:
    metadata:
      labels:
        app: phptest1
    spec:
      containers:
      - name: php
        image: gcr.io/helpful-lens-307104/php-test
        ports:
        - containerPort: 80
        env:
        - name: LISTEN
          value: "9000"
        - name: SESSION_SAVE_HANDLER
          value: "redis"
        - name: SESSION_SAVE_PATH
          value: "tcp://REDIS_HOST_IP:REDIS_HOST_PORT"
        - name: DB_NAME
          value: "test"
        - name: DB_USER
          value: "POSTGRES_USERNAME"
        - name: DB_PASSWORD
          value: "POSTGRES_PASSWORD"
        - name: DB_HOST
          value: "POSTGRES_HOST"
        - name: DB_CHARSET
          value: "utf8mb4"
        - name: MAX_CHILDREN
          value: "10"
        - name: START_SERVERS
          value: "4"
        - name: MAX_SPARE_SERVERS
          value: "4"
        - name: MAX_REQUESTS
          value: "500"  
      imagePullSecrets:
      - name: gcr-io
---        
apiVersion: v1
kind: Service
metadata:
  name: phptest1
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: phptest1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80    
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phptest1
  annotations:
    cloud.google.com/load-balancer-type: "External"
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: phptest1
      port:
        number: 80
  rules:
  - http:
      paths:
      - path:  /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: phptest1
            port:
              number: 80
